receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

  otlp:
    protocols:
      grpc:
      http:

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"

exporters:
  logging:
    # verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    # latency_histogram_buckets:
    #   [10ms, 100ms, 200ms, 400ms, 800ms, 1s, 1200ms, 1400ms, 1600ms, 1800ms, 2s, 5s, 7s]
    # dimensions:
    #   - name: http.method
    #   - name: http.status_code
    #   - name: http.target
    #   - name: http.url

service:
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [spanmetrics, batch]
      exporters: [jaeger, logging]
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus, logging]