version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USERNAME}" ]
      interval : 5s
      timeout : 5s
      retries : 5
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    image: products-backend
    environment:
      DATABASE_HOST: 172.17.0.1
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      ENABLE_CORS: ${ENABLE_CORS}
      OTLP_TRACE_EXPORTER_HOST: 172.17.0.1
    ports:
      - 3000:3000
  frontend:
    image: products-frontend
    ports:
      - 8080:80
  jaeger:
    image: jaegertracing/all-in-one:1.35
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318