version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USERNAME}" ]
      interval : 5s
      timeout : 5s
      retries : 5
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    image: products-backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      ENABLE_CORS: ${ENABLE_CORS}
    ports:
      - 3000:3000
  frontend:
    image: products-frontend
    ports:
      - 8080:80