version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DATABASE_NAME}",
          "-U",
          "${DATABASE_USERNAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./otel-collector/otel-collector-config-minimal.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - 4318:4318

  backend:
    depends_on:
      postgres:
        condition: service_healthy
      otel_collector:
        condition: service_started
    image: products-backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - 3000:3000

  frontend:
    depends_on:
      - backend
      - otel_collector
    image: products-frontend
    ports:
      - 8080:80