receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    # verbosity: detailed

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]