groups:
  - name: targets
    rules:
      - alert: service_down
        expr: probe_success{job="blackbox-exporter"} < 1
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service non-operational"
          description: "Service {{ $labels.instance }} is down."
