apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    isDefault: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.37.0
      exemplarTraceIdDestinations:
        # Internal link from exemplar popup
        - name: trace_id
          datasourceUid: jaeger-uid
        
        # External link from exemplar popup
        - name: trace_id
          url: 'http://localhost:16686/trace/$${__value.raw}'
          urlDisplayLabel: 'Jaeger'

  - name: Jaeger
    type: jaeger
    uid: jaeger-uid
    access: proxy
    url: http://jaeger:16686/
    editable: true
    isDefault: false