apiVersion: 1

templates:
  - orgID: 1
    name: opsgenie-message-template
    template: '{{ .GroupLabels.SortedPairs.Values | join " " }}{{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}'

groups:
  - orgId: 1
    name: service-alert-rules-group
    folder: service-alert-rules-folder
    interval: 1m
    rules:
      - uid: service-down-uid
        title: service-down
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prometheus-uid
            model:
              editorMode: builder
              expr: probe_success{job="blackbox-exporter"}
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: B
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: []
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: B
              type: reduce
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: B
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 2m
        isPaused: false

contactPoints:
  - orgId: 1
    name: opsgenie-contact-point
    receivers:
      - uid: opsgenie-uid
        type: opsgenie
        settings:
          apiKey: $GRAFANA_OPSGENIE_API_KEY
          apiUrl: https://api.opsgenie.com/v2/alerts
          message: |
            {{ template "opsgenie-message-template" . }}
          description: ''
          autoClose: true
          overridePriority: false
          sendTagsAs: both

policies:
  - orgId: 1
    receiver: opsgenie-contact-point

deleteContactPoints:
  - orgId: 1
    name: grafana-default-email