version: '3'
services:

  otel_collector:
    container_name: otel_collector
    image: mockserver/mockserver:5.15.0
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      MOCKSERVER_SERVER_PORT: 4318
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    ports:
      - 4318:4318
    volumes:
      - ../../mockserver/config:/config

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8787:8787
    volumes:
      - ../../keycloak/config/realms/import:/opt/keycloak/data/import
    entrypoint: [
      "/opt/keycloak/bin/kc.sh",
      "start-dev",
      "--import-realm",
      "--hostname-url=http://localhost:8787",
      "--http-port=8787"
    ]
